[package]
name = "simple-minecraft-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
bytes = "1.0"
anyhow = "1.0.98"
toml = "0.8.22"
serde = { version = "1.0.219", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"