[package]
name = "simple-minecraft-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
bytes = "1.0"
anyhow = "1.0.98"
serde_yaml = "0.9.34-deprecated"
serde = { version = "1.0.219", features = ["derive"] }