servers:
  vanilla_server:
    # if no 'bind' found, it binds to "0.0.0.0:25565" and "[::]:25565"
    server: "minecraft.example.com" # Port defaults to 25565
  modded_server:
    proxy_protocol: true # Enable proxy protocol v2
    bind:
      - "0.0.0.0:25565" # Only bind to IPv4
    server: "192.0.2.1:25656" # Port can be specified
health_check:
  enabled: true
  interval_sec: 5
  timeout_sec: 3
sorry_server:
  version: "§cOffline"
  motd:
    - "§cServer is currently offline."
    - "§bPlease try again later."
  kick_message:
    - "§cServer is currently offline."
    - "§bPlease try again later."