servers:
  vanilla_server:
    proxy_protocol: true
    # if no 'bind' found, it binds to "0.0.0.0:25565" and "[::]:25565"
    server: "minecraft.bqc0n.com"

#sorry_server:
#  version: "§cOffline"
#  motd:
#    - "§cServer is currently offline."
#    - "§bPlease try again later."
#  kick_message:
#    - "§cServer is currently offline."
#    - "§bPlease try again later."