servers:
  vanilla_server:
    proxy_protocol: true
    # if no 'bind' found, it binds to "0.0.0.0:25565" and "[::]:25565"
    server: "minecraft.bqc0n.com:25565"
health_check:
  enabled: true
  interval_sec: 5
  timeout_sec: 3
sorry_server:
  version: "Maintenance"
  motd:
    - "§cServer is currently offline."
    - "§bPlease try again later."
  kick_message:
    - "§cServer is currently offline."
    - "§bPlease try again later."