name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            arch_label: x86_64-linux
          - target: aarch64-unknown-linux-gnu
            arch_label: aarch64-linux

    steps:
      - uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-minecraft-proxy-${{ matrix.arch_label }}
          path: target/${{ matrix.target }}/release/simple-minecraft-proxy
